// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtlrFC871f7w0fGuQGTWB-oq5Idpkq0f4',
    appId: '1:863364334349:web:343eb09c5241f9bdb5e644',
    messagingSenderId: '863364334349',
    projectId: 'pos-demo-1',
    authDomain: 'pos-demo-1.firebaseapp.com',
    storageBucket: 'pos-demo-1.firebasestorage.app',
    measurementId: 'G-3C3T16VXTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADMglOuslwX4wKkvklKjpb1BuQ5xXu44Y',
    appId: '1:863364334349:android:5a038d5e858e451fb5e644',
    messagingSenderId: '863364334349',
    projectId: 'pos-demo-1',
    storageBucket: 'pos-demo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDze9Yva3j1Bv2ko_6I1L-K516ErDkAJC0',
    appId: '1:863364334349:ios:48725a1a72089e33b5e644',
    messagingSenderId: '863364334349',
    projectId: 'pos-demo-1',
    storageBucket: 'pos-demo-1.firebasestorage.app',
    iosBundleId: 'com.example.pos1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDze9Yva3j1Bv2ko_6I1L-K516ErDkAJC0',
    appId: '1:863364334349:ios:48725a1a72089e33b5e644',
    messagingSenderId: '863364334349',
    projectId: 'pos-demo-1',
    storageBucket: 'pos-demo-1.firebasestorage.app',
    iosBundleId: 'com.example.pos1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtlrFC871f7w0fGuQGTWB-oq5Idpkq0f4',
    appId: '1:863364334349:web:4d2dee5f8d43d677b5e644',
    messagingSenderId: '863364334349',
    projectId: 'pos-demo-1',
    authDomain: 'pos-demo-1.firebaseapp.com',
    storageBucket: 'pos-demo-1.firebasestorage.app',
    measurementId: 'G-B14THTM0ME',
  );

}